### ISSUE TITLE
Use \revsdnamepunct

### ISSUE THREAD

**Issue by moewew** [marcodaniel/biblatex-nejm#1]
If I'm not mistaken the `\renewbibmacro*{name:last-first}[4]` block
https://github.com/marcodaniel/biblatex-nejm/blob/288210762c720d39db8b94ffc28793f5c3e11826/nejm.bbx#L164-L183
could simply be replaced by the single line

```
\renewcommand*{\revsdnamepunct}{}
```

**Comment by DilumAluthge** [comment]
I think I can close this now. Let me know if I am not correct @moewew
