### ISSUE TITLE
License and date in documentation

### ISSUE THREAD

**Issue by moewew** [marcodaniel/biblatex-nejm#15]
It's really nice to see some development here.

While I was reading the documentation for v0.5 I realised that the date on the title page still says "2011/09/09". That might confuse people. I suggest to change that to the current date for the next release.

Furthermore the documentation claims
```
This package was tested with \biblatex verson 1.6.
```
If I'm not completely mistaken the recent update uses functionality of v3.8, so that should probably be changed. I tested the package with the current `biblatex` version 3.12 and it seems to work so far, so maybe that number can be bumped up.

I also noticed that the package is *author-maintained* as per LPPL (https://www.latex-project.org/lppl.txt) *author-maintained* packages are problematic, since it becomes harder to pass on the maintenance of a package to other people. Maybe it would be possible to ask @marcodaniel to waive this status.

---

I have also found a number of smaller issues that might be worth discussing. Would you prefer if I opened several small issues for those or one large "collection" issue?

**Comment by moewew** [comment]
It may be easier to simplify the
```
\def\biblatexnejmversionbbx{v0.6.0}
\def\biblatexnejmpackagenamebbx{nejm.bbx}
\def\biblatexnejmsvnbbx$#1: #2 #3 #4-#5-#6 #7 #8${#4/#5/#6\space }
\ProvidesFile{nejm.bbx}[\biblatexnejmsvnbbx$Id: nejm.bbx 30 2018-07-28 11:01:00Z marco $ \biblatexnejmversionbbx: \biblatexnejmpackagenamebbx]
```
to something like
```
\ProvidesFile{nejm.bbx}[2010/01/23 v0.6.0 biblatex bibliography style for the NEJM (MD/DA)]
```

**Comment by DilumAluthge** [comment]
Marco gave CTAN staff permission to name someone else as maintainer. CTAN has listed me as the primary maintainer, and has marked Marco as inactive.

I have made a PR (#16) with some of the changes you suggested.

For the other smaller issues: open a different GitHub issue for each one. That makes it easier for me to keep track of what has been done and what still needs to be done.

**Comment by DilumAluthge** [comment]
> It may be easier to simplify the
> 
> ```
> \def\biblatexnejmversionbbx{v0.6.0}
> \def\biblatexnejmpackagenamebbx{nejm.bbx}
> \def\biblatexnejmsvnbbx$#1: #2 #3 #4-#5-#6 #7 #8${#4/#5/#6\space }
> \ProvidesFile{nejm.bbx}[\biblatexnejmsvnbbx$Id: nejm.bbx 30 2018-07-28 11:01:00Z marco $ \biblatexnejmversionbbx: \biblatexnejmpackagenamebbx]
> ```
> 
> to something like
> 
> ```
> \ProvidesFile{nejm.bbx}[2010/01/23 v0.6.0 biblatex bibliography style for the NEJM (MD/DA)]
> ```

Can you open a pull request with these changes?

**Comment by DilumAluthge** [comment]
@moewew I think that we have resolved everything in this issue, so I will close it. If I am incorrect, please let me know and we can either re-open this issue or create new issues!
