### ISSUE TITLE
URL and urldate for @online sources

### ISSUE THREAD

**Issue by moewew** [marcodaniel/biblatex-nejm#18]
The documentation quotes the full NEJM style reference. Apparently there have been some subtle changes to the requirements since `biblatex-nejm` was first released. The documentation has

> 4. U.S. positions on selected issues at the third negotiating session of the Framework Convention on Tobacco Control. Washington, D.C.: Committee on Government Reform, 2002. (Accessed March
4, 2002, at http://www.house.gov/reform/min/inves_tobacco/index_accord.htm.)

but https://www.nejm.org/author-center/new-manuscripts has

> 4. Medicare: trends in fees, utilization, and expenditures for imaging services before and after implementation of the Deficit Reduction Act of 2005. Washington, DC: Government Accountability Office, September 2008. (http://www.gao.gov/new.items/d081102r.pdf.)

Note how the older version includes the access date of the URL and the new one does not. Is there any indication in newer published NEJM papers that the access date might still be required?

Following on from that, note how

https://github.com/marcodaniel/biblatex-nejm/blob/1f6b879af395589befe0a3a6e40a1a120b5918f5/biblatex-nejm.tex#L223-L231

makes use of the `addendum` field. In `biblatex`, the preferred way to give the URL is the `url` and `urldate` field.

If there is a decision on which format to follow for `@online` I can try to come up with a small pull request to that effect.

**Comment by DilumAluthge** [comment]
> Note how the older version includes the access date of the URL and the new one does not. Is there any indication in newer published NEJM papers that the access date might still be required?

So I just looked at the PDF of a paper published in NEJM in June 2019. Here is how they cited an online resource:
> 23.  UKPDS  risk  engine.  Oxford,  United  Kingdom:  Oxford Centre for Diabetes, En-docrinology and Metabolism, 2017 (https://www.dtu.ox.ac.uk/riskengine).

So I agree with you that NEJM seems to no longer require the access date. To stay consistent with NEJM, we should stop including the access date. Can you make a pull request @moewew?

**Comment by DilumAluthge** [comment]
I have transitioned the hosting of this package to: https://github.com/bcbi/biblatex-nejm
