### ISSUE TITLE
Driver for @incollection

### ISSUE THREAD

**Issue by moewew** [marcodaniel/biblatex-nejm#19]
At the moment the documentation uses `@article` to format a reference that is clearly an `@incollection`

https://github.com/marcodaniel/biblatex-nejm/blob/1f6b879af395589befe0a3a6e40a1a120b5918f5/biblatex-nejm.tex#L211-L221

Not only is that theoretically unsatisfying, it severely inhibits portability of `.bib` files for `biblatex-nejm`.

Given the required output, `biblatex-nejm` would probably have to include a modified driver for `@incollection`.

**Comment by DilumAluthge** [comment]
> Given the required output, `biblatex-nejm` would probably have to include a modified driver for `@incollection`.

Unfortunately I don't know enough about `biblatex` to write a driver from scratch. However, if you make a PR, I'm happy to review and merge it.

**Comment by DilumAluthge** [comment]
@moewew Now that pull request #20 has been merged, I think that this issue has been resolved. I will close this issue. Let me know if I should reopen it.
