### ISSUE TITLE
urldate field is ignored

### ISSUE THREAD

**Issue by daviewales** [marcodaniel/biblatex-nejm#3]
The accessed date for URLs is ignored.

It can be added back in using the technique described [here](https://tex.stackexchange.com/questions/194575/altering-date-format-in-references/194594#194594).

For instance:

```
\DeclareFieldFormat{urldate}{%
  [Accessed\addspace%
  \mkbibmonth{\thefield{urlmonth}}\addspace%
  \thefield{urlday}\addcomma\addspace%
  \thefield{url year}]}
```

(This would need to be tweaked a bit to match the NEJM URL format.)

**Comment by moewew** [comment]
I think it would be more beneficial to instead stop redefining the date macros as is done in
https://github.com/marcodaniel/biblatex-nejm/blob/288210762c720d39db8b94ffc28793f5c3e11826/nejm.bbx#L85-L99

In current versions of `biblatex` it is much easier to make dates print only the year, and it could also be made sure that the `urldate` is still in long form. Nowadays one would use
```
alldates=year, urldate=short,
```

Of course the `short` date format could be modified as necessary.

The style needs modifications for the name format in 3.3, and I assume that a few other things could be streamlined now that `biblatex` offers more functionalities out of the box.

**Comment by DilumAluthge** [comment]
I think that this can be closed now. Please let me know if I am not correct @daviewales @moewew
